experiment/barc_1/barc_1_estimator:
  ros__parameters:
    dt: 0.02

    estimate_accel: false

    ot_params:
      odom_topic: 'optitrack/odom'
      lin_accel_topic: 'optitrack/lin_accel'
      ang_accel_topic: 'optitrack/ang_accel'

      origin_x: 1.0
      origin_y: 1.0
      origin_z: 0.0
      origin_yaw: 0.5

      offset_long: -0.16
      offset_tran: 0.0
      offset_vert: 0.0
      offset_yaw: 0.0