# Simulator params:
experiment/barc_1/barc_1_simulator:
  ros__parameters:
    # Simulator time step
    dt: 0.01

    # delay: 0.1

    dynamics_config:
      model_name: 'dynamic_bicycle'

      discretization_method: 'rk4'

      wheel_dist_front: 0.13
      wheel_dist_rear: 0.13
      wheel_dist_center_front: 0.1
      wheel_dist_center_rear: 0.1
      bump_dist_front: 0.15
      bump_dist_rear: 0.15
      bump_dist_center: 0.1

      mass: 2.2187
      gravity: 9.81
      yaw_inertia: 0.02723

      # Tire model parameters:
      tire_model: 'pacejka'
      wheel_friction: 0.9
      pacejka_b_front: 5.0
      pacejka_c_front: 2.28
      pacejka_b_rear: 5.0
      pacejka_c_rear: 2.28

      simple_slip: false

      M: 10

    initial_config:
      # Initial position of car relative to track origin, initial heading is assumed to be 0 (body +x aligned with track +x)
      x:
        x: -1.0
        y: 0.0
        z: 0.0
      e:
        psi: 0.0
      v:
        v_long: 0.01