# Visualization parameters:
experiment/visualizer:
  ros__parameters:
    vehicle_namespaces: ['barc_1']

    global_plot_params:
      circuit: true

      figure_size: [1500, 750]

      show_lineplots: true

      state_data_fields: ['p.s', 'p.x_tran', 'v.v_long']
      state_units: ['m', 'm', 'm/s']
      
      input_data_fields: ['u_a', 'u_steer']
      input_units: ['m/s^2', 'rad']

      buffer_length: 50
      keep_history: false

      draw_period: 0.05

    barc_1:
      color: 'b'
      vehicle_draw_L: 0.37
      vehicle_draw_W: 0.195

      show_traces: true

      show_state: true
      state_topics: ['est_state']
      state_trace_styles: ['dash']

      show_input: true
      input_topics: ['ecu']
      input_trace_styles: ['solid']

      show_pred: true
      pred_topics: ['pred', 'ref']
      pred_styles: ['solid', 'dash']

      show_point_set: false

      show_cov: false

      simulated: true