experiment/barc_2/barc_2_control:
  ros__parameters:
    dt: 0.1
    n_laps: 5

    pid_steer_params:
      Kp: 1.0  # 1.0
      Ki: 0.005  # 0.15
      Kd: 0.0  # 0.0
      u_min: -0.436
      u_max: 0.436
      du_min: -4.5
      du_max: 4.5
      noise: false
      noise_max: 0.2
      noise_min: -0.2
      periodic_disturbance: false
      disturbance_period: 2.1
      disturbance_amplitude: 0.4
    pid_speed_params:
      Kp: 1.0  # 2.2
      Ki: 0.0  # 0.5
      Kd: 0.0  # 0.02
      x_ref: 1.0
      u_min: -2.0
      u_max: 2.0
      du_min: -10.0
      du_max: 10.0
      noise: false
      noise_max: 0.5
      noise_min: -0.5
      periodic_disturbance: false
      disturbance_period: 1.3
      disturbance_amplitude: 0.5