# Simulator params:
experiment/barc_2/barc_2_optitrack:
  ros__parameters:
    # Simulator time step
    dt: 0.01
    name: 'optitrack'
    dropout_rate: 0.0

    config:
      n_bound: 0.5

      x_std: 0.001
      y_std: 0.001
      z_std: 0.001
      roll_std: 0.001
      pitch_std: 0.001
      yaw_std: 0.001

      v_long_std: 0.001
      v_tran_std: 0.001
      v_vert_std: 0.001
      roll_dot_std: 0.001
      pitch_dot_std: 0.001
      yaw_dot_std: 0.001

      origin_x: 1.0
      origin_y: 1.0
      origin_z: 0.0
      origin_yaw: 0.5

      offset_long: -0.16
      offset_tran: 0.0
      offset_vert: 0.0
      offset_yaw: 0.0
