/experiment/barc_1/est_state:
  reliability: best_effort
  history: keep_all

/experiment/barc_1/sim_state:
  reliability: best_effort
  history: keep_all

/experiment/barc_1/state_input_log:
  reliability: best_effort
  history: keep_all

/experiment/barc_1/ecu:
  reliability: best_effort
  history: keep_all

/experiment/barc_1/optitrack/odom:
  reliability: best_effort
  history: keep_all

/experiment/barc_1/optitrack/lin_accel:
  reliability: best_effort
  history: keep_all

/experiment/barc_1/optitrack/ang_accel:
  reliability: best_effort
  history: keep_all

/experiment/barc_1/pred:
  reliability: best_effort
  history: keep_all

/experiment/barc_1/ss:
  reliability: best_effort
  history: keep_all
